name: mgmt_contacts
version: 0.0.0
author: Dzenan Ridjanovic
description: mgmt_contacts application that uses dartling for its model.
homepage: http://ondart.me/
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dartling:
    git: https://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: https://github.com/dzenanr/dartling_default_app.git
